### ISSUE TITLE
Copy-Paste typo in test

### ISSUE THREAD

**Issue by klememi** [MI-AFP/hw05#2]
it "matches with AnyInternal" $ do
      (AnyInternal ~~ esInternal1) `shouldBe` True
      (AnyInternal ~~ esExternal)  `shouldBe` False
      (AnyInternal ~~ esCombined)  `shouldBe` True
      (AnyInternal ~~ Unknown)     `shouldBe` False
      (AnyInternal ~~ Combined [esExternal,Unknown]) `shouldBe` False
    it "matches with AnyInternal" $ do
      (AnyExternal ~~ esInternal1) `shouldBe` False
      (AnyExternal ~~ esExternal)  `shouldBe` True
      (AnyExternal ~~ esCombined)  `shouldBe` True
      (AnyExternal ~~ Unknown)     `shouldBe` False
      (AnyExternal ~~ Combined [esInternal1,Unknown]) `shouldBe` False
    it "matches with AnyInternal" $ do
      (Any ~~ esInternal1) `shouldBe` True
      (Any ~~ esExternal)  `shouldBe` True
      (Any ~~ esCombined)  `shouldBe` True
      (Any ~~ Unknown)     `shouldBe` True
      (Any ~~ Combined [esInternal1,Unknown]) `shouldBe` True

copy-paste typos in *titles*

**Comment by MarekSuchanek** [comment]
😢 ouch, this is bad one... thanks

https://github.com/MI-AFP/hw05/commit/a4ae3c2e729a8b759856a6d2a6521de8bd3cb67c
