### ISSUE TITLE
Problematic definition of modulo arithmetic

### ISSUE THREAD

**Issue by shanemat** [MI-AFP/hw05#5]
Hi! 🙂 I have looked on your fixed version of tests and I would like you to specify the definition of your modulo arithmetic.

As far as I have been taught, the modulo of _n_ must be in range from _0_ to _n - 1_.  However, according to your tests, this does not hold - see

`(RomanNumeral "-IV" quotRem RomanNumeral "III") shouldBe (RomanNumeral "-I", RomanNumeral "-I")`  ~ (-4 mod 3 = -1) ~ I would say it should be 2.

Also I doubt anyone in any of our math courses have even used a negative number as base for modulo operation, but then I would say the result should be in range from _n + 1_ to _0_. However, the tests state following 

`(RomanNumeral "X" quotRem RomanNumeral "-III") shouldBe (RomanNumeral "-III", RomanNumeral "I")` ~ (10 mod -3 = 1) ~ I (and even Prelude) say that it should be -2.

Could you please clarify this? Thank you 🙂

**Comment by MarekSuchanek** [comment]
Hello, there is a difference between `div`/`mod` and `quot`/`rem`.

See: https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation

**Comment by shanemat** [comment]
> Hello, there is a difference between `div`/`mod` and `quot`/`rem`.
> 
> See: https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation

Oh, my bad. I did not know about this, thanks for pointing out 🙂
